services:
  mediainfo-debug:
    image: ${MINFO_DEBUG_IMAGE:-mediainfo-debug}
    container_name: ${MEDIAINFO_DEBUG_CONTAINER_NAME:-mediainfo-debug}
    build:
      context: .
      target: debug
    privileged: true
    ports:
      - "${HOST_PORT:-28888}:${PORT:-28888}"
      - "${DLV_HOST_PORT:-2345}:2345"
    environment:
      PORT: "${PORT:-28888}"
      REQUEST_TIMEOUT: "${REQUEST_TIMEOUT:-20m}"
    working_dir: ${PWD:-/opt/minfo}
    volumes:
      - /lib/modules:/lib/modules:ro
      - .:${PWD:-/opt/minfo}
      - ${MEDIA_PATH_1:-./test-media}:/media:ro
    restart: unless-stopped
